name: "difftrace"
description: "Change detection for uv monorepos — find affected packages from git diff"

inputs:
  base:
    description: "Base ref to diff against"
    required: false
    default: "origin/main"
  lock-file:
    description: "Path to uv.lock file"
    required: false
    default: "uv.lock"
  exclude-packages:
    description: "Comma-separated list of packages to exclude from the affected set"
    required: false
    default: ""
  no-dev:
    description: "Exclude dev dependencies from the dependency graph"
    required: false
    default: "false"
  no-optional:
    description: "Exclude optional dependencies from the dependency graph"
    required: false
    default: "false"
  direct-only:
    description: "Only output directly changed packages, skip transitive dependents"
    required: false
    default: "false"
  root-triggers:
    description: "Comma-separated list of additional file/dir patterns that trigger test_all (e.g. 'Dockerfile,docker/'). Append / for directory prefixes."
    required: false
    default: ""
  verbose:
    description: "Enable debug logging to stderr"
    required: false
    default: "false"

outputs:
  affected:
    description: "JSON array of affected package names"
    value: ${{ steps.difftrace.outputs.affected }}
  matrix:
    description: 'JSON object for strategy.matrix (e.g. {"package": [...]})'
    value: ${{ steps.difftrace.outputs.matrix }}
  has_affected:
    description: '"true" if any packages are affected, "false" otherwise'
    value: ${{ steps.difftrace.outputs.has_affected }}
  test_all:
    description: '"true" if root config changed and all packages should be tested'
    value: ${{ steps.difftrace.outputs.test_all }}

branding:
  icon: "git-branch"
  color: "orange"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install difftrace
      shell: bash
      run: pip install "${{ github.action_path }}"

    - name: Validate inputs
      shell: bash
      run: |
        if [ ! -f "${{ inputs.lock-file }}" ]; then
          echo "::error::Lock file not found: ${{ inputs.lock-file }}"
          exit 1
        fi
        if ! git rev-parse --verify "${{ inputs.base }}" >/dev/null 2>&1; then
          echo "::warning::Base ref '${{ inputs.base }}' cannot be resolved — difftrace may fail. Try 'git fetch' or checkout with fetch-depth: 0."
        fi

    - name: Run difftrace
      id: difftrace
      shell: bash
      run: |
        set -euo pipefail
        FLAGS=""
        if [ -n "${{ inputs.exclude-packages }}" ]; then
          IFS=',' read -ra PKGS <<< "${{ inputs.exclude-packages }}"
          for pkg in "${PKGS[@]}"; do
            pkg=$(echo "$pkg" | xargs)
            if [ -n "$pkg" ]; then
              FLAGS="$FLAGS --exclude $pkg"
            fi
          done
        fi
        if [ "${{ inputs.no-dev }}" = "true" ]; then
          FLAGS="$FLAGS --no-dev"
        fi
        if [ "${{ inputs.no-optional }}" = "true" ]; then
          FLAGS="$FLAGS --no-optional"
        fi
        if [ "${{ inputs.direct-only }}" = "true" ]; then
          FLAGS="$FLAGS --direct-only"
        fi
        if [ -n "${{ inputs.root-triggers }}" ]; then
          IFS=',' read -ra TRIGGERS <<< "${{ inputs.root-triggers }}"
          for trigger in "${TRIGGERS[@]}"; do
            trigger=$(echo "$trigger" | xargs)
            if [ -n "$trigger" ]; then
              FLAGS="$FLAGS --root-trigger $trigger"
            fi
          done
        fi
        if [ "${{ inputs.verbose }}" = "true" ]; then
          FLAGS="$FLAGS --verbose"
        fi
        result=$(difftrace --base "${{ inputs.base }}" --lock-file "${{ inputs.lock-file }}" $FLAGS --json)
        affected=$(echo "$result" | python3 -c "import sys, json; print(json.dumps(json.load(sys.stdin)['affected']))")
        test_all=$(echo "$result" | python3 -c "import sys, json; print(str(json.load(sys.stdin)['test_all']).lower())")
        matrix=$(echo "$result" | python3 -c "import sys, json; print(json.dumps({'package': json.load(sys.stdin)['affected']}))")

        if [ "$affected" = "[]" ]; then
          has_affected="false"
        else
          has_affected="true"
        fi

        echo "affected=$affected" >> "$GITHUB_OUTPUT"
        echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
        echo "has_affected=$has_affected" >> "$GITHUB_OUTPUT"
        echo "test_all=$test_all" >> "$GITHUB_OUTPUT"
